	<div id="footer">
		<p class="clear">&copy; 2010. Anatoly, Dino, Goran, Pontus, Sinan | <a href="http://validator.w3.org/check?uri=referer" class="under">HTML</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" class="under">CSS</a>
		<br>Design: 
		<a href="http://openwebdesign.org/viewdesign.phtml?id=5363&referer=%2Fsearch.php%3Fvalidtype%3D%26contrast%3Dlightondark%26pricolor%3D%26seccolor%3D%26category%3Dbusiness%26css%3Dyes%26search%3Dsearch%26page%3D8">
		Utah Website Design</a>.</p>
	</div><!--End footer-->